// /lib/genreMap.js

// ✅ Turkish → Jikan Genre ID Map
const genreMap = {
  aksiyon: 1,
  macera: 2,
  komedi: 4,
  dram: 8,
  drama: 8,
  büyü: 16,
  fantastik: 10,
  doğaüstü: 37,
  "doğaüstü güçler": 37,
  gizem: 7,
  gerilim: 41,
  korku: 14,
  "bilim kurgu": 24,
  askeri: 38,
  romantik: 22,
  romantizm: 22,
  psikolojik: 40,
  spor: 30,
  okul: 23,
  müzik: 19,
  seinen: 42,
  shounen: 27,
  shoujo: 25,
  josei: 43,
  mecha: 18,
  oyun: 11,
  uzay: 29,
  vampir: 32,
  tarihi: 13,
  çocuk: 15,
  parodi: 20,
  polisiye: 39,
  "süper güç": 31,
  "yaşamdan kesitler": 36,
};

export default genreMap;
